services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service

  product-service:
    build:
      context: ./product-service
    container_name: product-service

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    depends_on:
      - user-service
      - product-service

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      - user-service
      - cart-service

  ui-service:
    build:
      context: ./ui-service
    container_name: ui-service
    environment:
      USER_SERVICE_URL: http://user-service:5001
      PRODUCT_SERVICE_URL: http://product-service:5002
      CART_SERVICE_URL: http://cart-service:5003
      PAYMENT_SERVICE_URL: http://payment-service:5004
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - payment-service