apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ui-to-backend
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["product","cart","user","payment"]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ui

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cart-to-payment
spec:
  podSelector:
    matchLabels:
      app: payment
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cart


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-ui
spec:
  podSelector:
    matchLabels:
      app: ui
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0