apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-ui
spec:
  podSelector:
    matchLabels:
      app: ui
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ui-to-backend
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["user","product","cart","payment"]
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ui

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-payment-to-cart
spec:
  podSelector:
    matchLabels:
      app: cart
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: payment

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cart-to-product
spec:
  podSelector:
    matchLabels:
      app: product
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cart

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cart-to-user
spec:
  podSelector:
    matchLabels:
      app: user
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cart

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53

