apiVersion: apps/v1
kind: Deployment
metadata:
  name: charan-capstone-app-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: us-west1-docker.pkg.dev/citric-kit-489316-g6/charan-ar/ui-service:latest
        ports:
        - containerPort: 5000
          
        resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "300m"

        env:
        - name: USER_SERVICE_URL
          value: "http://user-service:5001"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:5002"
        - name: CART_SERVICE_URL
          value: "http://cart-service:5003"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:5004"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer


--- 
# 🔹 HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: charan-capstone-app-ui-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20